# Generated by Django 3.0.3 on 2020-03-03 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_auto_20200303_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 3, 15, 5, 24, 514820, tzinfo=utc)),
        ),
    ]
