# Generated by Django 3.0.3 on 2020-03-04 03:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0003_auto_20200303_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 3, 56, 41, 89059, tzinfo=utc)),
        ),
    ]
