# Generated by Django 3.0.3 on 2020-03-04 05:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_auto_20200304_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 5, 54, 9, 746401, tzinfo=utc)),
        ),
    ]
