# Generated by Django 3.0.3 on 2020-03-04 06:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0006_auto_20200304_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 6, 5, 17, 506864, tzinfo=utc)),
        ),
    ]
