# Generated by Django 3.0.3 on 2020-03-04 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0007_auto_20200304_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 6, 50, 6, 265618, tzinfo=utc)),
        ),
    ]
