# Generated by Django 3.0.3 on 2020-03-09 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_system', '0012_auto_20200304_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_SEED',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Server_Random', models.CharField(max_length=512, null=True)),
                ('Client_Random', models.CharField(max_length=512, null=True)),
                ('SEED', models.CharField(max_length=512, null=True)),
                ('expires', models.DateTimeField(blank=True, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
