# Generated by Django 3.0.3 on 2020-03-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0014_auto_20200311_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_seed',
            name='Client_Random',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_seed',
            name='Server_Random',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
