# Generated by Django 3.0.3 on 2020-03-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0016_auto_20200311_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_seed',
            name='Client_Random',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='user_seed',
            name='Server_Random',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
